export enum LegalStructure {
  LIMITED_COMPANY,
  TRUST,
  FUND,
  PARTNERSHIP,
  SOLE_PROPRIETORSHIP,
  ASSOCIATION,
  COOPERATIVE,
  OTHER,
}

export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING_DOCUMENTS = 'PENDING_DOCUMENTS',
  PENDING = 'PENDING',
}

export enum IndustryType {
  FINANCE,
  REAL_ESTATE,
  SERVICES,
  MANUFACTURING,
  TECHNOLOGY,
  HEALTHCARE,
  EDUCATION,
  RETAIL,
  AGRICULTURE,
  CONSTRUCTION,
  TRANSPORTATION,
  OTHER,
}
